version: '3'

services:
  craft:
    build: .
    volumes:
      - ./web/:/var/www/html/
      - ./templates/:/var/www/templates/
      - ./config/:/var/www/config/
      - ./storage/:/var/www/storage/
      - ./translations/:/var/www/translations/
      - ./composer.json:/var/www/composer.json
      - ./composer.lock:/var/www/composer.lock
    ports:
      - 80:80
    restart: always
