version: '3'

services:
  craft:
    build: .
    container_name: docker-craft-nginx
    image: eivindml/docker-craft-nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./src/composer.json:/www/composer.json
      - ./src/composer.lock:/www/composer.lock
      - ./src/config/:/www/config/
      - ./src/storage/:/www/storage/
      - ./src/templates/:/www/templates/
      - ./src/translations/:/www/translations/
      - ./src/web/:/www/html/
