version: '3'

services:
  craft:
    container_name: docker-craft
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
    volumes:
      - ./src/web/:/var/www/html/
      - ./src/templates/:/var/www/templates/
      - ./src/config/:/var/www/config/
      - ./src/storage/:/var/www/storage/
      - ./src/translations/:/var/www/translations/
      - ./src/composer.json:/var/www/composer.json
      - ./src/composer.lock:/var/www/composer.lock
    ports:
      - 80:80
    restart: always
